<script src="/cms-assets/static/js/components/dark.js"></script>
<script src="/cms-assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="/cms-assets/compiled/js/app.js"></script>
<script src="/cms-assets/extensions/jquery/jquery.min.js"></script>
<script src="/cms-assets/extensions/datatables.net/jquery.dataTables.min.js"></script>
<script src="/cms-assets/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="/cms-assets/static/js/pages/datatables.js"></script>
<!-- <script src="/cms-assets/extensions/apexcharts/apexcharts.min.js"></script> -->
<!-- <script src="/cms-assets/static/js/pages/dashboard.js"></script> -->